[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycalculatordapp = "HSAuJpP1cX2nPvfJ5qwAnSTSn8zWzqmP7J1b22ZdSKrF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rakshit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
